condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
newline_style = "Unix"
reorder_impl_items = true
trailing_comma = "Always"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
overflow_delimited_expr = true
