[package]
name = "reactance"
version = "0.1.0-canary"
edition = "2018"
publish = false

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
nom = { version = "5.1.2", default-features = false }
panic-persist = "0.2.1"
stm32g4 = { version = "0.11.0", features = ["stm32g474", "rt"] }

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "z"
